### ISSUE TITLE
Already secure images being proxied

### ISSUE THREAD

**Issue by tn5421** [RX14/camo.cr#5]
This is inelegant behavior, using resources that don't need to be used, because only http origin requests should be proxied in the first place.  Please do your voodoo regex magic to ensure https resources aren't proxied unnecessarily.

**Comment by RX14** [comment]
This isn't an issue with camo.cr, its up to the web server to decide which images are sent through the proxy.

**Comment by matiasgarciaisaia** [comment]
@tn5421 I agree with @RX14 it should be a client's responsibility to not ask for what's not needed.

Anyways, if you want to avoid secure images to being proxied in the camo-side of the moon, you can check #4 to see how I've implemented redirects for some resources. You should be able to change that code just a bit to make camo redirect those requests instead of proxying them.

I'd accept a PR about that in my dirty fork if you make that configurable 👍
